src/components/testbutton/testButton.scss
src/scss/_typography.scss
src/scss/_variables.scss
src/scss/global.scss
src/views/about/About.tsx
src/views/about/about.scss
src/views/form/form.scss

merga till dev för att få med scss variablar + ändringar, css inte helt fixad men underlättar för oss alla.

142 desktopmobile whitespace and text

---

src/components/contentcomponent/contentComponent.tsx
src/components/formcomponent/formComponent.tsx
src/components/resultscomponent/resultsComponent.tsx
src/views/form/Form.tsx

clean code

---

src/components/contentcomponent/contentComponent.tsx
src/components/contentcomponent/contentcomponent.scss

Co-Authored-By: Emil Arvidsson <92728538+KarlEmilArvid@users.noreply.github.com>

changed section -> label, clicks working

---

src/components/contentcomponent/contentcomponent.scss
src/components/image/image.scss
src/views/form/form.scss

css image section fix

---

src/views/personas/Personas.tsx
src/views/personas/personas.scss

kryss-knapp inlagd

---

src/views/personas/Personas.tsx
src/views/personas/personas.scss

Ytterligare styling fixad

---

src/components/contentcomponent/contentComponent.tsx
src/components/formcomponent/formComponent.tsx
src/components/resultscomponent/resultsComponent.tsx

Co-Authored-By: Emil Arvidsson <92728538+KarlEmilArvid@users.noreply.github.com>

Firebase answers and result functionality working

---

src/views/about/About.tsx

Co-Authored-By: Emil Arvidsson <92728538+KarlEmilArvid@users.noreply.github.com>
Co-Authored-By: Williamlof <83575469+Williamlof@users.noreply.github.com>

import educations from firestore

---

src/components/contentcomponent/contentComponent.tsx
src/components/contentcomponent/contentcomponent.scss
src/components/resultscomponent/resultsComponent.tsx
src/views/form/form.scss

css height fixes

---

src/components/header/header.scss

hamb text final fix

---

src/App.tsx
src/components/personacontent/personacontent.scss
src/views/personas/personas.scss

Scroll för mobile och desktop klart

238 finslip för scss

---

src/components/formcomponent/formComponent.scss
src/components/personacontent/personacontent.scss

scroll helt fixad samt styling till texterna i personas korten

stylat text

---

src/components/contentcomponent/contentcomponent.scss

space between bottom to avoid pressing 'backbutton' on mobile

Quiz nav fix

---

src/components/header/header.tsx

Problem with menu (mobile) on scroll, leaves an empty row at the top.
Fixed by adding if statement to the scrollFunction.

fixed issue with scroll when drop down menu is open on mobile

---

src/scss/_layout.scss
src/views/form/form.scss
src/views/home/home.scss

Removed the majority of the border styling around cards. Both for mobile and desktop. 
Most of the related code as been comented out for now.

Fix lines mobile view

---

src/components/header/header.scss
src/components/testbutton/testButton.scss
src/scss/_typography.scss
src/scss/global.scss
src/views/about/about.scss
src/views/education/education.scss
src/views/educations/educations.scss
src/views/home/home.scss

Har fixat IBM font till h1,h2 och buttons och roboto till P taggarna

Desktop typography fix 482

---

src/views/educations/Educations.tsx

Set loop to false and removed courseWrapper from targets. The animation now runs only once.

Set loop to false and removed courseWrapper from targets

---

src/components/resultscomponent/resultToggleComponent.tsx
src/components/resultscomponent/resultsComponent.scss

Reversed direction, position centered and new toggle color (lightBlue)

457 result page arrows

---

package-lock.json
package.json
src/views/home/Home.tsx

Removed the second part of the animation. The typewriter effect is now set on the entire text.

452 home title animation

---

src/components/header/header.tsx
src/views/personas/Personas.tsx

bugfix: rendering persona card based on url query

bugfix: rendering persona card

---

src/components/transitionWrapper/transitionWrapper.tsx

Removed all animations on all components, but transtions between routes

fix: animation

---

src/components/resultscomponent/resultsComponent.tsx
src/views/educations/Educations.tsx
src/views/educations/educations.scss

I have filtered out some courses. Frontend-distans and Javascript-distans. 
Both from the test and from the "våra utbildningar" page too. 
I also added the "specialist inom nätverkssäkerhet" as an option on the test with what i think is the correct links etc. 
Educations.scss file also got some very small changes to the grid to fit with 4 courses/educations instead of 6. 
Everything is just commented or filtered out, so it's still there if needed for the future too.

Filtered out some courses no longer needed.
